import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AppLayoutClient from "./AppLayoutClient"; // Importas el nuevo componente

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Synapsse",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AppLayoutClient> {/* Usas el nuevo componente de cliente */}
          {children}
        </AppLayoutClient>
      </body>
    </html>
  );
}