spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/synapsse}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:santiago}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

synapsse:
  security:
    jwt:
      secret: ${JWT_SECRET:c3luYXBzc2UtZGVmYXVsdC1qd3Qtc2VjcmV0LXNob3VsZC1iZS1iYXNlNjQ=}
      expiration: ${JWT_EXPIRATION:86400000}
