spring:
  datasource:
    url: jdbc:postgresql://72.61.33.27:5432/synapsse?ssl=false&TimeZone=UTC
    username: postgres
    password: santiago
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    open-in-view: false
    show-sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

synapsse:
  security:
    jwt:
      secret: ${JWT_SECRET:c3luYXBzc2UtZGVmYXVsdC1qd3Qtc2VjcmV0LXNob3VsZC1iZS1iYXNlNjQ=}
      expiration: ${JWT_EXPIRATION:86400000}
